spring:
  application:
    name: rest-identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/identity_db
    username: iammahbubalam
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
#  data:
#    redis:
#      host: localhost
#      port: 6379


app:
  jwt:
    access-token-expiration-sec: 900       # 15 minutes
    refresh-token-expiration-ms: 604800000 # 7 days
    refresh-token-cookie-name: refresh-token
  security:
    login:
      lockout:
        enabled: true
        max-attempts: 5
        duration-min: 15
    jwk:
      rotation:
        enabled: true
        interval-hours: 24
        keys-to-keep: 2